In [4]:
import numpy as np

In [5]:
arr=np.array(
    [[2.0,3.0,6.0],
     [4.0,"hi",20.0]])

In [6]:
print(f"Type:{type(arr)}")

Type:<class 'numpy.ndarray'>


In [7]:
print(f"Dimensions:{arr.ndim}")

Dimensions:2


In [8]:
print(f"Size:{arr.shape}")

Size:(2, 3)


In [9]:
print(f"Type:{arr.dtype}")

Type:<U32


In [10]:
print(f"Size:{arr.size}")

Size:6


In [11]:
arr=np.array([2.,3.,4.])
print(arr)

[2. 3. 4.]


In [12]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.arange(start=5,stop=20,step=5))

[ 5 10 15]


In [14]:
print(np.empty((4,3)))

[[1.76016064e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [15]:
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
print(np.eye((4)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
print(np.diag([2,3,5,5.0]))

[[2. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [19]:
print(np.random.rand(2,3),end="\n\n")

[[0.35456031 0.63945377 0.0752695 ]
 [0.99219485 0.1222201  0.31270202]]



In [20]:
print(np.random.uniform(-2,3,3),end='\n\n')

[ 2.52888839  0.63163508 -1.30611258]



In [21]:
print(np.random.randn(3,1),end="\n\n")

[[ 0.46464694]
 [-0.06921502]
 [ 1.07236117]]



In [22]:
a=np.arange(10)**2

In [23]:
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [24]:
print(a[::-1])

[81 64 49 36 25 16  9  4  1  0]


In [25]:
a=np.arange(24).reshape(4,6)

In [26]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [27]:
a[2,:6]

array([12, 13, 14, 15, 16, 17])

In [28]:
a[1:5,-1]

array([11, 17, 23])

In [29]:
arr=np.random.randn(3,4)

In [30]:
print(arr)

[[-0.24038551  0.45420272 -0.25124917  0.09861186]
 [-1.20273769 -0.63212914 -1.53896451  0.68962794]
 [ 1.7886317   0.98168612  0.37291548 -0.53950684]]


In [31]:
print(arr.ravel())

[-0.24038551  0.45420272 -0.25124917  0.09861186 -1.20273769 -0.63212914
 -1.53896451  0.68962794  1.7886317   0.98168612  0.37291548 -0.53950684]


In [32]:
print(arr.T)

[[-0.24038551 -1.20273769  1.7886317 ]
 [ 0.45420272 -0.63212914  0.98168612]
 [-0.25124917 -1.53896451  0.37291548]
 [ 0.09861186  0.68962794 -0.53950684]]


In [33]:
print(arr.reshape(2,6))

[[-0.24038551  0.45420272 -0.25124917  0.09861186 -1.20273769 -0.63212914]
 [-1.53896451  0.68962794  1.7886317   0.98168612  0.37291548 -0.53950684]]


In [34]:
arr_mod=arr.reshape(1,-80)

In [35]:
print(arr_mod)

[[-0.24038551  0.45420272 -0.25124917  0.09861186 -1.20273769 -0.63212914
  -1.53896451  0.68962794  1.7886317   0.98168612  0.37291548 -0.53950684]]


In [36]:
arr_mod.shape

(1, 12)

In [83]:
a=np.arange(5)
b=a
id(b)

140482131368416

In [84]:
id(a)

140482131368416

In [85]:
print(a)

[0 1 2 3 4]


In [86]:
print(b)

[0 1 2 3 4]


In [87]:
id(b)

140482131368416

In [88]:
c=a.view

In [89]:
c==a

array([False, False, False, False, False])

In [90]:
print(c)

<built-in method view of numpy.ndarray object at 0x7fc48b8999e0>


In [91]:
print(a)

[0 1 2 3 4]


In [92]:
d=a.copy()

In [93]:
print(id(d))

140481371937408


In [94]:
print(id(a))

140482131368416


In [95]:
print(d)

[0 1 2 3 4]


In [96]:
print(a)

[0 1 2 3 4]


In [97]:
a[2]=99

In [98]:
d[0]=12

In [99]:
d

array([12,  1,  2,  3,  4])

In [100]:
a

array([ 0,  1, 99,  3,  4])

In [112]:
a=np.arange(9).reshape(3,3)

In [113]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
b=np.arange(11,20).reshape(3,-1)

In [121]:
a*b

array([[  0,  12,  26],
       [ 42,  60,  80],
       [102, 126, 152]])

In [122]:
a**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [128]:
a=np.arange(24).reshape(4,-1)

In [129]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [130]:
a.sum()

276

In [132]:
a.sum(axis=0)

array([36, 40, 44, 48, 52, 56])

In [133]:
a.sum(axis=1)

array([ 15,  51,  87, 123])

In [135]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
        8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
        3.58491285e+09, 9.74480345e+09]])

In [136]:
a=np.arange(81).reshape(27,3)

In [137]:
b=np.arange(45).reshape(3,15)

In [ ]:
a.bot

# Practice questions

In [1]:
import numpy as np
arr=np.arange(100,200,10).reshape(5,2)

In [2]:
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [23]:
mat=np.arange(1,10).reshape(3,3)

In [24]:
def column_3(mat):
        arr=mat[:,-1]
        return arr

In [25]:
print(column_3(mat))

[3 6 9]


In [32]:
arr=[30,60,90]
i=2

In [33]:
def replace_col(mat,i,arr):
    mat[:,(i)]=arr
    return mat

In [34]:
print(replace_col(mat,i,arr))

[[ 1  2 30]
 [ 4  5 60]
 [ 7  8 90]]


In [40]:
mat=np.arange(1,10).reshape(3,-1)

In [41]:
def swap_col(mat,i,j):
    arr=mat[:,i].copy()
    mat[:,i]=mat[:,j]
    mat[:,j]=arr
    return mat

In [42]:
swap_col(mat,0,2)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [43]:
x=[0.707,0.5,0.866]

In [44]:
y=[0,0.5,0.866]

In [58]:
import math
def cos_angle(x,y):
    sum=0
    a1=0
    a2=0
    l=len(x)
    for i in range(l):
        mul=x[i]*y[i]
        sum+=mul
        a1=a1+(x[i]*x[i])
        a2=a2+(y[i]*y[i])
    prod=a1*a2
    prod=math.sqrt(prod)
    sum=sum/prod
    return sum

In [60]:
cos_angle(x,x)

1.0

In [79]:
import numpy as np
mat = [[0.0222, 0.0444, 0.0667],
       [0.0889, 0.1111, 0.1333],
       [0.1556, 0.1778, 0.2000]]

In [80]:
def marginal(m):
    margx=np.sum(m,axis=0)
    margy=np.sum(m,axis=1)
    return(margx,margy)
        

In [81]:
marginal(mat)

(array([0.2667, 0.3333, 0.4   ]), array([0.1333, 0.3333, 0.5334]))